### DISCUSSION TITLE
Building whl files

### DISCUSSION THREAD

**Discussion by FanofVS** [PyAV-Org/PyAV#1361] [1. Help] [answered]
After running command 'pip install av', we can find that a whl file is downloaded, and pyav is installed by extracting it.
![截屏2024-04-01 下午5 39 53](https://github.com/PyAV-Org/PyAV/assets/43821502/bccb409f-833b-4b78-b5d7-0c46c6430c4f)
As we can see, the installation is like this:
![截屏2024-04-01 下午5 42 40](https://github.com/PyAV-Org/PyAV/assets/43821502/47d192e9-c144-4fa0-b9f3-8cd66595b6a3)
I would like to know how to build such a whl file that contains all depended libraries(in the pic above, the ffmpeg libraries under the directory 'av.libs'), so that I can build one with my own ffmpeg version

**Comment by WyattBlue** [comment, marked as answer]
To build your own wheels, you would fork [pyav-ffmpeg](https://github.com/PyAV-Org/PyAV-ffmpeg), edit [the build script](https://github.com/PyAV-Org/pyav-ffmpeg/blob/main/scripts/build-ffmpeg.py) to your liking, then make a GitHub release. You would then change `scripts/ffmpeg-6.1.json` to point to your new release url. Then you would run this bash command to generate the wheels:

```
      - name: Build wheels
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BEFORE_ALL_LINUX: yum install -y alsa-lib libxcb
          CIBW_BEFORE_BUILD: python scripts/fetch-vendor.py --config-file scripts/ffmpeg-6.1.json /tmp/vendor
          CIBW_BEFORE_BUILD_WINDOWS: python scripts\fetch-vendor.py --config-file scripts\ffmpeg-6.1.json C:\cibw\vendor
          CIBW_ENVIRONMENT_LINUX: LD_LIBRARY_PATH=/tmp/vendor/lib:$LD_LIBRARY_PATH PKG_CONFIG_PATH=/tmp/vendor/lib/pkgconfig
          CIBW_ENVIRONMENT_MACOS: PKG_CONFIG_PATH=/tmp/vendor/lib/pkgconfig LDFLAGS=-headerpad_max_install_names
          CIBW_ENVIRONMENT_WINDOWS: INCLUDE=C:\\cibw\\vendor\\include LIB=C:\\cibw\\vendor\\lib PYAV_SKIP_TESTS=unicode_filename
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: delvewheel repair --add-path C:\cibw\vendor\bin -w {dest_dir} {wheel}
          CIBW_SKIP: cp36-* pp36-* pp38-win* *-musllinux*
          CIBW_TEST_COMMAND: mv {project}/av {project}/av.disabled && python -m unittest discover -t {project} -s tests && mv {project}/av.disabled {project}/av
          CIBW_TEST_REQUIRES: numpy
          # skip tests when there are no binary wheels of numpy
          CIBW_TEST_SKIP: pp* *_i686
        run: |
          pip install cibuildwheel delvewheel
          cibuildwheel --output-dir dist
        shell: bash
```

Or make your changes in a forked repo and let github actions make the release for you.
